pub const CHUNK_PIXEL_SIZE: f32 = 100.0;
pub const TILE_SCALE: f32 = 3.0;
pub const TILE_PIXEL_SIZE: f32 = 32.0;
pub const TOTAL_TILE_SCALE_SIZE: f32 = TILE_PIXEL_SIZE * TILE_SCALE + 4.0;
pub const CHUNK_TILE_SPAN_COUNT: i32 = (CHUNK_PIXEL_SIZE / TOTAL_TILE_SCALE_SIZE) as i32;
